
development:

  adapter: postgresql

  encoding: unicode

  database: 2witters_development

  host: localhost


test:

  adapter: postgresql

  encoding: unicode

  database: 2witters_test

  host: localhost


production:

  adapter: postgresql

  encoding: unicode

  database: 2witters_production

  host: localhost
